### ISSUE TITLE
Get the code mirror jsp path value from property file

### ISSUE THREAD

**Issue by hamakhaa** [contento3/Projects#46]
Get the code mirror jsp path value from property file.This file is being used within the code in TemplateUIManager as:

```
        StringBuffer urlStr = new StringBuffer("http://localhost:8080/jsp/codemirror");
```

This needs not to be hard coded. A properties file called templateconfig.properties should be created in the site project in the root package. 

The value must be read from the file. This will be stored as a key value pair in the property file.

**Comment by mehtabghani** [comment]
this task is almost done but there is little problem I am facing, when I place templateconfig.properties in sites project it is not accessible
 final CachedTypedProperties languageProperties = CachedTypedProperties.getInstance("languages.properties");
in this code, but when I place templateconfig.properties in core the code is working properly. kindly suggest me if there is some thing i missed?

**Comment by hamakhaa** [comment]
You dont have to place that in sites project.Thats supposed to be in core project and it will be accessible from sites.
