### ISSUE TITLE
Create a ui to display group list in cmsadmin.

### ISSUE THREAD

**Issue by hamakhaa** [contento3/Projects#89]
Create a ui to display group list in cmsadmin. For examples have a look at different listings like Page listing and Layout listing etc.

**Comment by hamakhaa** [comment]
GroupUIManager

1.Description is showing null as value when editing.
2.Table width must be 100%.
3.The number of rows for table must be dynamic.
4.There should be screen heading
5.I am getting red error mark when I am trying to delete the groups that have users associated with it.This needs to be handled properly.There should be an warning notification when user try to delete them.

**Comment by mehtabghani** [comment]
what exactly warning notification should be?
and there is other problem group id is used in 2 others tables as foreign key so we have to need some criteria or service  to delete group_id from the other 2 tables as well..

**Comment by hamakhaa** [comment]
notification should be like : "Group "groupname here" cannot be deleted as users are associated with the group."

**Comment by hamakhaa** [comment]
Yes I think you are talking about the GROUP_AUTHORITIES.That needs to be checked as well.Yes I think we need to implement the group authorities as well.
