### ISSUE TITLE
Image library ui and account id addition

### ISSUE THREAD

**Issue by hamakhaa** [contento3/Projects#99]
This requires the following:
1. Addition of account_id in image_library table.
   2.A combobox to display all the image libraries when the user adds a new image.This is required so that we can store an image in a library.
2. Whenever the new image is created the image needs to be associated with an image.

**Comment by mehtabghani** [comment]
" 2.Whenever the new image is created the image needs to be associated with an image." 
image needs to be associated with an image.. I didn't get?

**Comment by hamakhaa** [comment]
Sorry I mean the image should be associated to library.
